---
title: "model_proj3"
author: "Chenze-Li"
date: "2021/3/4"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)

covid <- read_csv("https://covid19.who.int/WHO-COVID-19-global-data.csv")
covid$WHO_region<-as.factor(covid$WHO_region)


#model1

library(gdata)
GDP<-read.table("GDP.txt",header=T)
GDP$Date<-paste(year(ymd(GDP$Date1)),month(ymd(GDP$Date1)),sep="-")
new_case<-filter(covid,Country_code=="US")
new_case$Date<-paste(year(ymd(new_case$Date_reported)),month(ymd(new_case$Date_reported)),sep="-")
new_case1<-summarise(group_by(new_case,Date),new_case=sum(New_cases))
new_case1<-new_case1[1:13,]
data<-inner_join(new_case1,GDP,by="Date")
library(nlme)
library(lmerTest)
data$Date<-as.factor(data$Date)
model1<-lm(GDP~log(new_case),data=data)
summary(model1)
```
```{r}
#model2
model2_da<-filter(covid,Country_code=="US")
pre<-model2_da[1:397,]$New_cases
test<-model2_da[398:427,]$New_cases
ar<-acf(pre)
ar
p<-pacf(pre)
p
res<-ar(pre, method="mle")
res
resm<-arima(pre, order=c(11,0,0))
pred<-predict(resm, n.ahead=30, se.fit=TRUE)
pic<-as.data.frame(cbind(Observed=test, 
      Predict=pred$pred, 
      SE=pred$se))
library(ggplot2)
ggplot(data=pic)+
  geom_line(aes(1:30,Observed,colour="red"))+
  geom_line(aes(1:30,Predict,colour="blue"))
```
```{r}
#model3

covid_en<-filter(covid,Country_code=="GB")
covid_cn<-filter(covid,Country_code=="CN")
covid_en_un<-filter(covid_en,"2020-03-13"<=Date_reported,Date_reported<="2020-03-23")
covid_en_lo<-filter(covid_en,"2020-03-23"<=Date_reported,Date_reported<="2020-04-02")
covid_cn_un<-filter(covid_cn,"2020-01-13"<=Date_reported,Date_reported<="2020-01-23")
covid_cn_lo<-filter(covid_cn,"2020-01-23"<=Date_reported,Date_reported<="2020-02-02")
covid_en_un$rate<-c(NA,covid_en_un$New_cases[2:11]/covid_en_un$Cumulative_cases[1:10])
covid_en_lo$rate<-c(NA,covid_en_lo$New_cases[2:11]/covid_en_lo$Cumulative_cases[1:10])
covid_en_un$status<-rep(0,11)
covid_en_lo$status<-rep(1,11)
covid_cn_un$rate<-c(NA,covid_cn_un$New_cases[2:11]/covid_cn_un$Cumulative_cases[1:10])
covid_cn_lo$rate<-c(NA,covid_en_lo$New_cases[2:11]/covid_cn_lo$Cumulative_cases[1:10])
covid_cn_un$status<-rep(0,11)
covid_cn_lo$status<-rep(1,11)

data2<-as.data.frame(rbind(rbind(covid_en_un[2:11,],covid_en_lo[2:11,]),rbind(covid_cn_un[2:11,],covid_cn_lo[2:11,])))

data2$status<-as.factor(data2$status)
data2$Country_code<-as.factor(data2$Country_code)


fit2<-aov(rate~status+Country_code+status:Country_code,data=data2)
summary(fit2)
#causal inference
data2$status = relevel(data2$status,ref='0')
fit_ = glm(status~Country_code,family = binomial,data = data2)
prob = fit_$fitted.values
pscore = ifelse(data2$rate=='1',prob,(1-prob))
weight = 1/pscore

model_new = aov(rate~status+Country_code+status:Country_code,data = data2,weights = weight)
summary(model_new)
```
```{r}
#causal inference
data3<-read_csv("C:/Users/Tony Li/Desktop/data_c.csv",col_names = T)
data3f<-read_csv("C:/Users/Tony Li/Desktop/data_c1.csv",col_names = T)
colnames(data3f)[1]<-"country_code"
colnames(data3)[1]<-"country_code"
sumn<-function(x){
  return (sum(x,na.rm=T))
}
data3f$days<-apply(data3f[,3:431],1,sumn)
pos<-function(x){
  return (which(x==2))
}
data3_pos<-apply(data3[,3:431],1,pos)
names(data3_pos)<-1:186

data3_pos1<-sapply(data3_pos,length)
data3_pos1<-data3_pos1[which(data3_pos1>=22)]
data3_pos<-data3[as.integer(names(data3_pos1)),]
posq<-function(x){
  return (which(x==2)[1])
}
pos1<-apply(data3_pos[,3:431],1,posq)
date<-colnames(data3_pos)[pos1]
date<-as.Date(date,"%d%b%Y")
date<-data.frame(country_code=data3_pos$country_code,date=date)
library(countrycode)
library(ISOcodes)
covid_<-covid
covid_$country_code<-countrycode(covid$Country,origin = "country.name",destination = "iso3c",warn = TRUE)
c<-c(integer(0))
for (i in 1:153){
  c<-c(c,which(covid_$country_code==data3_pos$country_code[i]))
  
}

covid_<-covid_[c,]
newd<-inner_join(covid_, data3_pos, by = "country_code")
newd<-inner_join(newd,date, by = "country_code")
newd<-newd[,c(1:10,440)]

day<-unique(newd$date)
code<-unique(newd$country_code)

data4<-data.frame(integer(0))
for (i in 1:49){
covid_temp<-filter(newd,country_code==code[i])

covid_temp_un<-filter(covid_temp,as.Date(day[i])-10<=Date_reported,Date_reported<=day[i])
covid_temp_lo<-filter(covid_temp,day[i]<=Date_reported,Date_reported<=as.Date(day[i])+10)

covid_temp_un$rate<-c(NA,covid_temp_un$New_cases[2:11]/covid_temp_un$Cumulative_cases[1:10])
covid_temp_lo$rate<-c(NA,covid_temp_lo$New_cases[2:11]/covid_temp_lo$Cumulative_cases[1:10])
covid_temp_un$status<-rep(0,11)
covid_temp_lo$status<-rep(1,11)

temp1<-as.data.frame(rbind(covid_temp_un[2:11,],covid_temp_lo[2:11,]))
data4<-as.data.frame(rbind(data4,temp1))
}

```

```{r}
data4<-data.frame(integer(0))
i=50
covid_temp<-filter(newd,country_code==code[i])

covid_temp_un<-filter(covid_temp,as.Date(day[i])-10<=Date_reported,Date_reported<=day[i])
covid_temp_lo<-filter(covid_temp,day[i]<=Date_reported,Date_reported<=as.Date(day[i])+10)

covid_temp_un$rate<-c(NA,covid_temp_un$New_cases[2:11]/covid_temp_un$Cumulative_cases[1:10])
covid_temp_lo$rate<-c(NA,covid_temp_lo$New_cases[2:11]/covid_temp_lo$Cumulative_cases[1:10])
covid_temp_un$status<-rep(0,11)
covid_temp_lo$status<-rep(1,11)

temp1<-as.data.frame(rbind(covid_temp_un[2:11,],covid_temp_lo[2:11,]))
data4<-as.data.frame(rbind(data4,temp1))
data4$status<-as.factor(data4$status)
data4$Country_code<-as.factor(data4$country_code)


pos2<-which(data4$rate==NaN|data4$rate==Inf)
data4<-filter(data4,!(country_code%in%unique(data4$country_code[pos2])))


fit3<-aov(rate~status+country_code,data=data4)
summary(fit3)

data4$status = relevel(data4$status,ref='0')
fit4 = glm(status~country_code,family = binomial,data = data4)
prob = fit4$fitted.values
pscore = ifelse(data4$rate=='1',prob,(1-prob))
weight = 1/pscore

model_new1= aov(rate~status+country_code,data = data4,weights = weight)
summary(model_new1)
```

